export const RECEIVE_LOGIN_RESPONSE = 'RECEIVE_LOGIN_RESPONSE'
export const LOGOUT = 'LOGOUT'

export const UPDATE_CALENDAR_VIEW = 'UPDATE_CALENDAR_VIEW'

export const TOGGLE_POPUP_VISIBLE = 'TOGGLE_POPUP_VISIBLE'
export const CHANGE_POPUP_TAB = 'CHANGE_POPUP_TAB'
export const CHANGE_ITEM_COUNT = 'CHANGE_ITEM_COUNT'
